fix: Fixes #1412 NoClassDefFoundError JdkDeserializers
Fixes error `Exception in thread "Global IO pool-3" java.lang.NoClassDefFoundError: Could not initialize class com.fasterxml.jackson.databind.deser.std.JdkDeserializers` that is due to dependencies of different versions.