Added extensive error handling when connection to localhost is refused but port and host ist correct:
19:00:56.793 SEVERE: [1] org.jitsi.videobridge.Main.main().287 Connection exception in component: JitsiVideobridge. host: localhost port: 5347 domain: localhost subdomain: jitsi-videobridge
19:00:56.794 SEVERE: [1] org.jitsi.videobridge.Main.main().293 Be aware that localhost might have multiple ips:
19:00:56.796 SEVERE: [1] org.jitsi.videobridge.Main.main().302 192.168.0.129
19:00:56.796 SEVERE: [1] org.jitsi.videobridge.Main.main().302 10.211.55.2
19:00:56.796 SEVERE: [1] org.jitsi.videobridge.Main.main().302 4006:7a50:c0a8:b329:e2f8:47ff:fe28:befc
19:00:56.798 SEVERE: [1] org.jitsi.videobridge.Main.main().302 2a02:810b:340:18d4:7824:d305:ec17:62
19:00:56.799 SEVERE: [1] org.jitsi.videobridge.Main.main().302 2a02:810b:340:18d4:e2f8:47ff:fe28:befc
19:00:56.799 SEVERE: [1] org.jitsi.videobridge.Main.main().302 fe80:0:0:0:e2f8:47ff:fe28:befc%en1
19:00:56.799 SEVERE: [1] org.jitsi.videobridge.Main.main().302 192.168.179.24
19:00:56.799 SEVERE: [1] org.jitsi.videobridge.Main.main().302 fe80:0:0:0:ca2a:14ff:fe13:94c9%en0
19:00:56.799 SEVERE: [1] org.jitsi.videobridge.Main.main().302 169.254.94.2
19:00:56.800 SEVERE: [1] org.jitsi.videobridge.Main.main().302 fe80:0:0:0:0:0:0:1%lo0
19:00:56.800 SEVERE: [1] org.jitsi.videobridge.Main.main().302 0:0:0:0:0:0:0:1
19:00:56.800 SEVERE: [1] org.jitsi.videobridge.Main.main().302 127.0.0.1
19:00:56.800 SEVERE: [1] util.UtilActivator.uncaughtException().108 An uncaught exception occurred in thread=Thread[main,5,main] and message was: java.net.ConnectException: Connection refused
org.xmpp.component.ComponentException: java.net.ConnectException: Connection refused
    at org.jivesoftware.whack.ExternalComponent.connect(ExternalComponent.java:272)
    at org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:221)
    at org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:201)
    at org.jitsi.videobridge.Main.main(Main.java:281)
Caused by: java.net.ConnectException: Connection refused
    at java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    at java.net.Socket.connect(Socket.java:589)
    at org.jivesoftware.whack.ExternalComponent.connect(ExternalComponent.java:151)
    ... 3 more